spring:
    application:
      name: ${artifactId}
      version: ${version}
    jmx.enabled: true
management:
    info:
      build.enabled: true
      java.enabled: true
      git.enabled: true
    endpoint:
      health:
        probes.enabled: true
        group:
          readiness.include: "*"
          liveness.include: livenessState,diskSpace,ping
    endpoints:
      jmx:
        exposure.include: "*"
      web:
        exposure.include: info, health

mtls:
  fail-if-no-verified: "\${MTLS_FAIL_IF_NO_VERIFIED:true}"
  # comma separated list of protected paths
  paths: "/cie,/cie2"

sil:
  notification:
    legacy:
      secret: "\${SIL_LEGACY_JWT_SECRET:bGVnYWN5Snd0IHNlY3JldA==}" # "legacyJwt secret"
      kid: "\${SIL_LEGACY_JWT_KID:kid}"
      subject: "\${SIL_LEGACY_JWT_SUBJECT:mocked-sil}"
      issuer: "\${SIL_LEGACY_JWT_ISSUER:piattaforma-unitaria}"
  actualization:
    legacy:
      auth:
        secret: "\${SIL_LEGACY_BASIC_TOKEN_SECRET:bGVnYWN5QmFzaWMgc2VjcmV0}" # "legacyBasic secret"
        expire-minutes: "\${SIL_LEGACY_BASIC_TOKEN_EXPIRATION_MINUTES:10}"

rest:
  defaults:
    connection-pool:
      size: "\${DEFAULT_REST_CONNECTION_POOL_SIZE:10}"
      size-per-route: "\${DEFAULT_REST_CONNECTION_POOL_SIZE_PER_ROUTE:5}"
      time-to-live-minutes: "\${DEFAULT_REST_CONNECTION_POOL_TIME_TO_LIVE_MINUTES:10}"
    timeout:
      connect-millis: "\${DEFAULT_REST_TIMEOUT_CONNECT_MILLIS:120000}"
      read-millis: "\${DEFAULT_REST_TIMEOUT_READ_MILLIS:120000}"
  auth:
    base-url: "\${AUTH_SERVER_BASE_URL:}/payhub"
    max-attempts: "\${AUTH_MAX_ATTEMPTS:3}" # It's counting also the first attempt
    wait-time-millis: "\${AUTH_WAIT_TIME_MILLIS:500}"
    print-body-when-error: "\${AUTH_PRINT_BODY_WHEN_ERROR:true}"
