spring:
    application:
      name: ${artifactId}
      version: ${version}
    jmx.enabled: true
management:
    info:
      build.enabled: true
      java.enabled: true
      git.enabled: true
    endpoint:
      health:
        probes.enabled: true
        group:
          readiness.include: "*"
          liveness.include: livenessState,diskSpace,ping
    endpoints:
      jmx:
        exposure.include: "*"
      web:
        exposure.include: info, health

sil:
  notification:
    legacy:
      secret: "\${SIL_LEGACY_JWT_SECRET:bGVnYWN5Snd0IHNlY3JldA==}" # "legacyJwt secret"
      kid: "\${SIL_LEGACY_JWT_KID:kid}"
      subject: "\${SIL_LEGACY_JWT_SUBJECT:mocked-sil}"
      issuer: "\${SIL_LEGACY_JWT_ISSUER:piattaforma-unitaria}"
  actualization:
    legacy:
      auth:
        secret: "\${SIL_LEGACY_BASIC_TOKEN_SECRET:bGVnYWN5QmFzaWMgc2VjcmV0}" # "legacyBasic secret"
        expire-minutes: "\${SIL_LEGACY_BASIC_TOKEN_EXPIRATION_MINUTES:10}"
