spring:
    application:
      name: ${artifactId}
      version: ${version}
    jmx.enabled: true
management:
    info:
      build.enabled: true
      java.enabled: true
      git.enabled: true
    endpoint:
      health:
        probes.enabled: true
        group:
          readiness.include: "*"
          liveness.include: livenessState,diskSpace,ping
    endpoints:
      jmx:
        exposure.include: "*"
      web:
        exposure.include: info, health
